import { useEffect, useMemo, useState } from 'react';
import { Download, Share2 } from 'lucide-react';
import toast from 'react-hot-toast';
import { pomodoroService } from '../services';

const buildShareSvg = (subject) => {
  const chapters = subject?.chapters || [];
  const chapterData = chapters.slice(0, 8).map((chapter, index) => ({
    label: `Ch ${index + 1}`,
    completion: chapter.completionPercentage || 0
  }));

  const bars = chapterData.map((item, index) => {
    const x = 70 + index * 64;
    const barHeight = Math.max(10, (item.completion / 100) * 110);
    const y = 420 - barHeight;
    return `
      <rect x="${x}" y="${y}" width="36" height="${barHeight}" rx="10" fill="${subject.color}" opacity="0.9" />
      <text x="${x + 18}" y="446" text-anchor="middle" font-size="12" fill="#9ca3af">${item.label}</text>
    `;
  }).join('');

  const completed = chapters.reduce((sum, chapter) => {
    return sum + (chapter.topics || []).filter((topic) => topic.completed).length;
  }, 0);
  const total = chapters.reduce((sum, chapter) => sum + (chapter.topics || []).length, 0);

  return `
    <svg xmlns="http://www.w3.org/2000/svg" width="900" height="540" viewBox="0 0 900 540">
      <defs>
        <linearGradient id="bg" x1="0%" y1="0%" x2="100%" y2="100%">
          <stop offset="0%" stop-color="#0a0e1a" />
          <stop offset="100%" stop-color="#141824" />
        </linearGradient>
      </defs>
      <rect width="900" height="540" fill="url(#bg)" />
      <text x="54" y="68" fill="#e5e7eb" font-size="34" font-family="Inter, sans-serif" font-weight="700">${subject.name}</text>
      <text x="54" y="105" fill="#9ca3af" font-size="20" font-family="Inter, sans-serif">Progress Snapshot</text>
      <circle cx="730" cy="86" r="46" fill="none" stroke="#1f2937" stroke-width="12" />
      <circle cx="730" cy="86" r="46" fill="none" stroke="${subject.color}" stroke-width="12" stroke-linecap="round" stroke-dasharray="${2 * Math.PI * 46}" stroke-dashoffset="${(2 * Math.PI * 46) * (1 - (subject.completionPercentage || 0) / 100)}" transform="rotate(-90 730 86)" />
      <text x="730" y="94" text-anchor="middle" fill="#e5e7eb" font-size="24" font-family="Inter, sans-serif" font-weight="700">${subject.completionPercentage || 0}%</text>
      <text x="54" y="164" fill="#9ca3af" font-size="17" font-family="Inter, sans-serif">Topics Completed</text>
      <text x="300" y="164" fill="#9ca3af" font-size="17" font-family="Inter, sans-serif">Time Spent</text>
      <text x="54" y="204" fill="#e5e7eb" font-size="34" font-family="Inter, sans-serif" font-weight="700">${completed}/${total || 0}</text>
      <text x="300" y="204" fill="#e5e7eb" font-size="34" font-family="Inter, sans-serif" font-weight="700">${subject.totalTimeSpent || 0}m</text>
      <rect x="54" y="250" width="792" height="250" rx="16" fill="#111827" stroke="#1f2937" />
      <text x="78" y="286" fill="#e5e7eb" font-size="18" font-family="Inter, sans-serif" font-weight="600">Chapter Completion</text>
      ${bars}
      <text x="54" y="510" fill="#6b7280" font-size="14" font-family="Inter, sans-serif">Generated by StudyTrack</text>
    </svg>
  `;
};

const svgToPngDownload = (svgString, filename) => {
  const blob = new Blob([svgString], { type: 'image/svg+xml;charset=utf-8' });
  const url = URL.createObjectURL(blob);
  const img = new Image();
  img.onload = () => {
    const width = 900;
    const height = 540;
    const canvas = document.createElement('canvas');
    const scale = window.devicePixelRatio || 1;
    canvas.width = width * scale;
    canvas.height = height * scale;
    const ctx = canvas.getContext('2d');
    ctx.setTransform(scale, 0, 0, scale, 0, 0);
    ctx.fillStyle = '#0a0e1a';
    ctx.fillRect(0, 0, width, height);
    img.width = width;
    img.height = height;
    ctx.drawImage(img, 0, 0, width, height);
    URL.revokeObjectURL(url);

    const pngUrl = canvas.toDataURL('image/png');
    const anchor = document.createElement('a');
    anchor.href = pngUrl;
    anchor.download = filename;
    anchor.click();
  };
  img.src = url;
};

const formatTime = (minutes = 0) => {
  const total = Math.max(0, Math.round(Number(minutes) || 0));
  const hours = Math.floor(total / 60);
  const mins = total % 60;
  return `${String(hours).padStart(2, '0')}:${String(mins).padStart(2, '0')}`;
};

const ShareProgressCard = ({ subjects }) => {
  const [selectedId, setSelectedId] = useState(subjects[0]?._id || '');
  const [todayMinutes, setTodayMinutes] = useState(0);
  const selectedSubject = useMemo(() => {
    return subjects.find((subject) => subject._id === selectedId) || subjects[0] || null;
  }, [selectedId, subjects]);

  const progressBars = useMemo(() => {
    const chapters = selectedSubject?.chapters || [];
    return chapters.slice(0, 8).map((chapter, index) => ({
      index: index + 1,
      value: chapter.completionPercentage || 0
    }));
  }, [selectedSubject]);

  const partsDone = useMemo(() => {
    const chapters = selectedSubject?.chapters || [];
    const completed = chapters.reduce((sum, chapter) => {
      return sum + (chapter.topics || []).filter((topic) => topic.completed).length;
    }, 0);
    const total = chapters.reduce((sum, chapter) => sum + (chapter.topics || []).length, 0);
    return { completed, total };
  }, [selectedSubject]);

  useEffect(() => {
    const loadToday = async () => {
      if (!selectedSubject) return;
      try {
        const today = new Date();
        const yyyy = today.getFullYear();
        const mm = String(today.getMonth() + 1).padStart(2, '0');
        const dd = String(today.getDate()).padStart(2, '0');
        const response = await pomodoroService.getDailyStats(`${yyyy}-${mm}-${dd}`);
        const breakdown = response.data?.subjectBreakdown || [];
        const match = breakdown.find((item) => item.name === selectedSubject.name);
        setTodayMinutes(match?.minutes || 0);
      } catch {
        setTodayMinutes(0);
      }
    };
    loadToday();
  }, [selectedSubject]);

  const handleExport = () => {
    if (!selectedSubject) return;
    const svg = buildShareSvg(selectedSubject);
    svgToPngDownload(svg, `${selectedSubject.name.toLowerCase().replace(/\s+/g, '-')}-progress.png`);
    toast.success('Progress card exported as PNG');
  };

  if (!subjects.length) return null;

  return (
    <div className="card overflow-hidden">
      <div className="grid grid-cols-1 lg:grid-cols-[220px_1fr] gap-6 items-start">
        <div>
          <h3 className="text-4xl font-display font-bold text-white leading-tight">
            Share
            <br />
            Your
            <br />
            Progress
          </h3>
          <p className="text-sm text-gray-500 mt-3">
            Export a stylish snapshot for your streaks.
          </p>
        </div>

        <div className="rounded-3xl border border-dark-border bg-[#0f111a] p-4">
          <div className="flex items-center justify-between mb-4">
            <div className="flex items-center gap-2 text-gray-300">
              <Share2 size={16} />
              <span className="text-sm">Share</span>
            </div>
            <div className="flex items-center gap-2">
              <select
                value={selectedSubject?._id || ''}
                onChange={(event) => setSelectedId(event.target.value)}
                className="input py-1.5"
              >
                {subjects.map((subject) => (
                  <option key={subject._id} value={subject._id}>{subject.name}</option>
                ))}
              </select>
              <button onClick={handleExport} className="btn-primary flex items-center gap-2">
                <Download size={16} />
                Export PNG
              </button>
            </div>
          </div>

          {selectedSubject && (
            <div className="rounded-3xl bg-gradient-to-br from-[#1a1f2b] to-[#141824] p-5 border border-dark-border">
              <div className="flex items-center justify-between mb-3">
                <div>
                  <h4 className="text-white font-semibold text-lg">{selectedSubject.name}</h4>
                  <p className="text-xs text-gray-400">Progress Snapshot</p>
                </div>
                <span className="text-sm text-rose-300 font-semibold">
                  {selectedSubject.completionPercentage || 0}%
                </span>
              </div>

              <div className="w-full h-2 rounded-full bg-dark-hover overflow-hidden mb-4">
                <div
                  className="h-full rounded-full bg-gradient-to-r from-rose-400 to-rose-300"
                  style={{ width: `${selectedSubject.completionPercentage || 0}%` }}
                />
              </div>

              <div className="grid grid-cols-3 gap-3 text-xs text-gray-300 mb-5">
                <div className="rounded-2xl bg-[#1e2230] p-3 border border-dark-border">
                  <p className="text-[10px] text-gray-400 mb-1">Spent Today</p>
                  <p className="text-sm font-semibold">{formatTime(todayMinutes)}</p>
                </div>
                <div className="rounded-2xl bg-[#1e2230] p-3 border border-dark-border">
                  <p className="text-[10px] text-gray-400 mb-1">Spent Total</p>
                  <p className="text-sm font-semibold">{formatTime(selectedSubject.totalTimeSpent || 0)}</p>
                </div>
                <div className="rounded-2xl bg-[#1e2230] p-3 border border-dark-border">
                  <p className="text-[10px] text-gray-400 mb-1">Parts Done</p>
                  <p className="text-sm font-semibold">{partsDone.completed}/{partsDone.total || 0}</p>
                </div>
              </div>

              <div className="h-32 flex items-end gap-3">
                {progressBars.length === 0 && (
                  <p className="text-xs text-gray-500">No chapters added yet.</p>
                )}
                {progressBars.map((bar) => (
                  <div key={`bar-${bar.index}`} className="flex flex-col items-center gap-1 flex-1">
                    <div
                      className="w-full rounded-2xl bg-rose-300/40"
                      style={{ height: `${Math.max(12, Math.round((bar.value / 100) * 112))}px` }}
                    />
                    <span className="text-[10px] text-gray-500">Ch {bar.index}</span>
                  </div>
                ))}
              </div>
            </div>
          )}
        </div>
      </div>
    </div>
  );
};

export default ShareProgressCard;
